// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CVAVT.Models;

public partial class ActivitaetKategorie
{
    public int ActivitaetIdfk { get; set; }

    public int KategorieIdfk { get; set; }

    public virtual Aktivitaet ActivitaetIdfkNavigation { get; set; }

    public virtual Kategorie KategorieIdfkNavigation { get; set; }
}