// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CVAVT.Models;

public partial class Kategorie
{
    public int KategorieId { get; set; }

    public string KategorieName { get; set; }

    public virtual ICollection<ActivitaetKategorie> ActivitaetKategorie { get; set; } = new List<ActivitaetKategorie>();
}