// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CVAVT.Models;

public partial class Leiter
{
    public int LeiterId { get; set; }

    public string LeiterName { get; set; }

    public virtual ICollection<Aktivitaet> Aktivitaet { get; set; } = new List<Aktivitaet>();
}