// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CVAVT.Models;

public partial class Teilnehmer
{
    public int TeilnehmerId { get; set; }

    public string TeilnehmerName { get; set; }

    public int AktivitaetIdfk { get; set; }

    public virtual Aktivitaet AktivitaetIdfkNavigation { get; set; }
}