// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CVAVT.Models;

public partial class ViewTeilnehmerIstAnzahl
{
    public int AktivitaetIdfk { get; set; }

    public int? TeilnehmerIstAnzahl { get; set; }
}