// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CVAVT.Models;

public partial class ZeigeNachLeiter2
{
    public string LeiterName { get; set; }

    public string AktivitaetenName { get; set; }

    public DateTime AktivitaetenDatum { get; set; }
}