// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CVAVT.Models;

public partial class ZeigeTeilnehmerListe
{
    public string AktivitaetenName { get; set; }

    public string TeilnehmerName { get; set; }

    public int? AktivitaetenMaxTeilnehmer { get; set; }
}